version: "3"
services:
  
  db:
    container_name: mongo-db
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    ports:
      - 27017:27017

  admin:
    container_name: mongo-admin
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - mongo-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
      - db

  api:
    build: .
    container_name: api
    command: nodemon server.js
    ports:
      - 3001:3001
    volumes:
      - .:/src/app
    environment:
      NODE_ENV: development
      PASSWORD_SECRET: my-nice-password
    depends_on:
      - db
    networks:
      - mongo-network

networks:
  mongo-network:

volumes:
  mongo-data: